services:
  dev-database:
    image: postgres
    container_name: dev_database
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      nestjs-network:
networks:
  nestjs-network:
