version: '3.9'
services:
  dev-database:
    image: postgres:15.0
    container_name: dev_database
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      nestjs-network:
networks:
  nestjs-network:
